development:
  adapter: mysql
  database: manage_development
  username: root
  password: password
  host: localhost
  port: 3306
 
test: &test
  adapter: mysql
  database: manage_test
  username: root
  password: password
  host: localhost
  port: 3306
  
staging:
  adapter: mysql
  database: 
  username: 
  password: 
  host: db.dev.frontfoot.net.au
  port: 3306
  
production:
  adapter: mysql
  database: manage_production
  username: manage_ruby
  password: fru1tyd00d
  host: localhost
  port: 3306
  

cucumber:
  <<: *test
