development:
  adapter: mysql
  database: manage_development
  username: root
  password:
  host: localhost
 
test: &test
  adapter: mysql
  database: manage_test
  username: root
  password: 
  host: localhost

cucumber:
  <<: *test
