development:
  :enable_starttls_auto: true
  :address: smtp.gmail.com
  :port: 587
  :domain: mymatebill.com
  :authentication: plain
  :user_name: support@mymatebill.com
  :password: W9wddp6lMSvl
production:
  :enable_starttls_auto: true
  :address: smtp.gmail.com
  :port: 587
  :domain: mymatebill.com
  :authentication: plain
  :user_name: support@mymatebill.com
  :password: W9wddp6lMSvl
