development:
  :enable_starttls_auto: true
  :address: smtp.gmail.com
  :port: 587
  :domain: hoolio.net
  :authentication: plain
  :user_name: error@hoolio.net
  :password: errpassorword
production:
  :enable_starttls_auto: true
  :address: smtp.gmail.com
  :port: 587
  :domain: hoolio.net
  :authentication: plain
  :user_name: error@hoolio.net
  :password: errpassorword
